server:
  port: 80
  max-http-header-size: 10240

shelf:
  swagger-open: true                #是否开启swagger (true/false)
  kaptcha-open: false               #是否开启登录时验证码 (true/false)
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 3600     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  sms-aliYun: false                  #短信发送接口（阿里云平台短信） 短信接口只能打开一个，否则会冲突，产生报错
  sms-jiGuang: true                #短信发送接口（极光推送平台短信） 短信接口只能打开一个，否则会冲突，产生报错

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: assets/**,pages/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  typeAliasesPackage: com.quick.shelf.modular.**.model
  mapper-locations: classpath:**/mapping/*.xml

log:
  path: shelf-logs